"""Stub cloud provider — exercises the full remote job lifecycle locally.

Use ``CLOUD_FINETUNE_BACKEND=stub`` to validate wiring without Modal/HF/RunPod.
Writes a marker adapter under ``data/adapters/{job_id}/`` so the registry can
surface ``adapted-{job_id}`` for downstream dictation tests.
"""

from __future__ import annotations

import json
import threading
import time
from pathlib import Path

from .base import CloudTrainProvider
from .types import RemoteJobRef, RemoteJobStatus, TrainRecipe

_LOCK = threading.Lock()
_STATE: dict[str, RemoteJobStatus] = {}


class StubCloudProvider(CloudTrainProvider):
    name = "stub"

    def validate_config(self) -> None:
        # Always available — no token required.
        return

    def submit(self, recipe: TrainRecipe, dataset_dir: Path) -> RemoteJobRef:
        if not dataset_dir.exists():
            raise FileNotFoundError(dataset_dir)
        remote_id = f"stub-{recipe.job_id}"
        with _LOCK:
            _STATE[remote_id] = RemoteJobStatus(
                status="queued",
                progress=0.0,
                logs_tail="stub: accepted recipe",
            )

        def _run() -> None:
            steps = [
                (0.15, "running", "stub: uploading dataset manifest"),
                (0.45, "running", "stub: allocating worker"),
                (0.75, "running", "stub: training LoRA (simulated)"),
                (1.0, "completed", "stub: packaging adapter"),
            ]
            for progress, status, log in steps:
                time.sleep(0.35)
                with _LOCK:
                    cur = _STATE.get(remote_id)
                    if cur and cur.status == "cancelled":
                        return
                    _STATE[remote_id] = RemoteJobStatus(
                        status=status,  # type: ignore[arg-type]
                        progress=progress,
                        logs_tail=log,
                        adapter_uri=f"stub://adapters/{recipe.job_id}",
                    )

        threading.Thread(target=_run, daemon=True).start()
        return RemoteJobRef(
            provider=self.name,
            remote_id=remote_id,
            metadata={
                "job_id": recipe.job_id,
                "dataset_id": recipe.dataset_id,
                "base_model": recipe.base_model,
                "dataset_dir": str(dataset_dir),
            },
        )

    def poll(self, ref: RemoteJobRef) -> RemoteJobStatus:
        with _LOCK:
            st = _STATE.get(ref.remote_id)
            if not st:
                return RemoteJobStatus(status="failed", error="Unknown remote job")
            return RemoteJobStatus(
                status=st.status,
                progress=st.progress,
                error=st.error,
                adapter_uri=st.adapter_uri,
                logs_tail=st.logs_tail,
            )

    def download_adapter(self, ref: RemoteJobRef, dest_dir: Path) -> Path:
        dest_dir.mkdir(parents=True, exist_ok=True)
        marker = {
            "provider": self.name,
            "remote_id": ref.remote_id,
            "note": (
                "Stub adapter marker only — not a real PEFT checkpoint. "
                "Wire modal/hf_jobs/runpod for production training."
            ),
            "metadata": ref.metadata,
        }
        (dest_dir / "adapter_config.json").write_text(
            json.dumps(
                {
                    "peft_type": "LORA",
                    "base_model_name_or_path": f"openai/whisper-{ref.metadata.get('base_model', 'tiny')}",
                    "stub": True,
                },
                indent=2,
            )
        )
        (dest_dir / "STUB_ADAPTER.json").write_text(json.dumps(marker, indent=2))
        (dest_dir / "README.md").write_text(
            "# Stub cloud adapter\n\nGenerated by CLOUD_FINETUNE_BACKEND=stub.\n"
        )
        return dest_dir

    def cancel(self, ref: RemoteJobRef) -> None:
        with _LOCK:
            st = _STATE.get(ref.remote_id)
            if st and st.status in {"queued", "running"}:
                _STATE[ref.remote_id] = RemoteJobStatus(
                    status="cancelled",
                    progress=st.progress,
                    logs_tail="stub: cancelled",
                )
